<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Inertia\Inertia;

class StrategyRegistryController extends Controller
{
    /**
     * Affiche le registre de toutes les stratégies.
     *
     * Pour l'instant : données simulées structurées comme StrategyRegistry.java.
     * Plus tard : lecture des fichiers batch-results/ ou API Java.
     */
    public function index()
    {
        $strategies = [
            // ── LIVE ─────────────────────────────────────────────
            [
                'id' => 'SQ_TR_EU_L_H1_177_v2.1.0',
                'shortName' => 'TR-EU-L-177',
                'family' => 'TR',
                'status' => 'live',
                'sharpe' => 1.89,
                'profitFactor' => 2.45,
                'winRate' => 62.3,
                'maxDrawdown' => 12.5,
                'robustness' => 85,
                'symbol' => 'EUR/USD',
                'timeframe' => 'H1',
                'direction' => 'LONG',
                'cumulativePnl' => 4230,
                'wfStatus' => 'ok',
                'wfDays' => 3,
                'tradesCount' => 147,
                'created' => '2025-11-12',
            ],
            [
                'id' => 'SQ_TR_GB_L_H1_042_v2.1.0',
                'shortName' => 'TR-GB-L-042',
                'family' => 'TR',
                'status' => 'live',
                'sharpe' => 2.12,
                'profitFactor' => 2.88,
                'winRate' => 58.7,
                'maxDrawdown' => 9.8,
                'robustness' => 91,
                'symbol' => 'GBP/USD',
                'timeframe' => 'H1',
                'direction' => 'LONG',
                'cumulativePnl' => 5870,
                'wfStatus' => 'ok',
                'wfDays' => 7,
                'tradesCount' => 203,
                'created' => '2025-10-05',
            ],
            [
                'id' => 'SQ_MR_UC_S_H4_008_v1.3.0',
                'shortName' => 'MR-UC-S-008',
                'family' => 'MR',
                'status' => 'live',
                'sharpe' => 1.45,
                'profitFactor' => 1.92,
                'winRate' => 55.1,
                'maxDrawdown' => 15.2,
                'robustness' => 72,
                'symbol' => 'USD/CAD',
                'timeframe' => 'H4',
                'direction' => 'SHORT',
                'cumulativePnl' => 2180,
                'wfStatus' => 'due',
                'wfDays' => 38,
                'tradesCount' => 89,
                'created' => '2025-12-01',
            ],

            // ── PAPER ────────────────────────────────────────────
            [
                'id' => 'SQ_BT_AU_L_H1_023_v1.0.0',
                'shortName' => 'BT-AU-L-023',
                'family' => 'BT',
                'status' => 'paper',
                'sharpe' => 1.67,
                'profitFactor' => 2.12,
                'winRate' => 59.4,
                'maxDrawdown' => 11.1,
                'robustness' => 78,
                'symbol' => 'AUD/USD',
                'timeframe' => 'H1',
                'direction' => 'LONG',
                'cumulativePnl' => 950,
                'wfStatus' => 'ok',
                'wfDays' => 5,
                'tradesCount' => 34,
                'created' => '2026-01-15',
            ],
            [
                'id' => 'SQ_MM_GJ_L_M15_155_v1.0.0',
                'shortName' => 'MM-GJ-L-155',
                'family' => 'MM',
                'status' => 'paper',
                'sharpe' => 0.92,
                'profitFactor' => 1.35,
                'winRate' => 51.8,
                'maxDrawdown' => 18.4,
                'robustness' => 55,
                'symbol' => 'GBP/JPY',
                'timeframe' => 'M15',
                'direction' => 'LONG',
                'cumulativePnl' => 340,
                'wfStatus' => 'ok',
                'wfDays' => 2,
                'tradesCount' => 67,
                'created' => '2026-02-10',
            ],
            [
                'id' => 'SQ_TR_UC_S_D1_071_v1.0.0',
                'shortName' => 'TR-UC-S-071',
                'family' => 'TR',
                'status' => 'paper',
                'sharpe' => 1.34,
                'profitFactor' => 1.78,
                'winRate' => 56.2,
                'maxDrawdown' => 14.0,
                'robustness' => 68,
                'symbol' => 'USD/CAD',
                'timeframe' => 'D1',
                'direction' => 'SHORT',
                'cumulativePnl' => 1250,
                'wfStatus' => 'due',
                'wfDays' => 42,
                'tradesCount' => 28,
                'created' => '2026-03-01',
            ],

            // ── BACKTEST ─────────────────────────────────────────
            [
                'id' => 'SQ_NW_EU_B_H1_004_v1.0.0',
                'shortName' => 'NW-EU-B-004',
                'family' => 'NW',
                'status' => 'backtest',
                'sharpe' => 2.45,
                'profitFactor' => 3.12,
                'winRate' => 64.9,
                'maxDrawdown' => 8.3,
                'robustness' => 94,
                'symbol' => 'EUR/USD',
                'timeframe' => 'H1',
                'direction' => 'BOTH',
                'cumulativePnl' => 0,
                'wfStatus' => 'ok',
                'wfDays' => 0,
                'tradesCount' => 312,
                'created' => '2026-04-12',
            ],
            [
                'id' => 'SQ_CT_GJ_S_H1_012_v1.0.0',
                'shortName' => 'CT-GJ-S-012',
                'family' => 'CT',
                'status' => 'backtest',
                'sharpe' => 1.81,
                'profitFactor' => 2.05,
                'winRate' => 53.4,
                'maxDrawdown' => 16.7,
                'robustness' => 71,
                'symbol' => 'GBP/JPY',
                'timeframe' => 'H1',
                'direction' => 'SHORT',
                'cumulativePnl' => 0,
                'wfStatus' => 'ok',
                'wfDays' => 0,
                'tradesCount' => 198,
                'created' => '2026-04-28',
            ],
            [
                'id' => 'GEN_TR_AU_L_H1_001_v1.0.0',
                'shortName' => 'GEN-TR-AU-L-001',
                'family' => 'TR',
                'status' => 'backtest',
                'sharpe' => 1.55,
                'profitFactor' => 1.88,
                'winRate' => 57.6,
                'maxDrawdown' => 13.1,
                'robustness' => 66,
                'symbol' => 'AUD/USD',
                'timeframe' => 'H1',
                'direction' => 'LONG',
                'cumulativePnl' => 0,
                'wfStatus' => 'ok',
                'wfDays' => 0,
                'tradesCount' => 156,
                'created' => '2026-05-01',
            ],

            // ── DEV ──────────────────────────────────────────────
            [
                'id' => 'GEN_MR_UC_B_H4_001_v1.0.0',
                'shortName' => 'GEN-MR-UC-B-001',
                'family' => 'MR',
                'status' => 'dev',
                'sharpe' => 0.0,
                'profitFactor' => 0.0,
                'winRate' => 0.0,
                'maxDrawdown' => 0.0,
                'robustness' => 0,
                'symbol' => 'USD/CAD',
                'timeframe' => 'H4',
                'direction' => 'BOTH',
                'cumulativePnl' => 0,
                'wfStatus' => 'ok',
                'wfDays' => 0,
                'tradesCount' => 0,
                'created' => '2026-05-18',
            ],
            [
                'id' => 'GEN_BT_EU_S_H1_002_v1.0.0',
                'shortName' => 'GEN-BT-EU-S-002',
                'family' => 'BT',
                'status' => 'dev',
                'sharpe' => 0.0,
                'profitFactor' => 0.0,
                'winRate' => 0.0,
                'maxDrawdown' => 0.0,
                'robustness' => 0,
                'symbol' => 'EUR/USD',
                'timeframe' => 'H1',
                'direction' => 'SHORT',
                'cumulativePnl' => 0,
                'wfStatus' => 'ok',
                'wfDays' => 0,
                'tradesCount' => 0,
                'created' => '2026-05-19',
            ],
            [
                'id' => 'GEN_NW_GJ_B_M5_003_v1.0.0',
                'shortName' => 'GEN-NW-GJ-B-003',
                'family' => 'NW',
                'status' => 'dev',
                'sharpe' => 0.0,
                'profitFactor' => 0.0,
                'winRate' => 0.0,
                'maxDrawdown' => 0.0,
                'robustness' => 0,
                'symbol' => 'GBP/JPY',
                'timeframe' => 'M5',
                'direction' => 'BOTH',
                'cumulativePnl' => 0,
                'wfStatus' => 'ok',
                'wfDays' => 0,
                'tradesCount' => 0,
                'created' => '2026-05-19',
            ],

            // ── RETIRED ──────────────────────────────────────────
            [
                'id' => 'SQ_MM_UC_L_H1_031_v1.5.0',
                'shortName' => 'MM-UC-L-031',
                'family' => 'MM',
                'status' => 'retired',
                'sharpe' => 0.67,
                'profitFactor' => 1.12,
                'winRate' => 48.3,
                'maxDrawdown' => 22.1,
                'robustness' => 32,
                'symbol' => 'USD/CAD',
                'timeframe' => 'H1',
                'direction' => 'LONG',
                'cumulativePnl' => -1240,
                'wfStatus' => 'ok',
                'wfDays' => 0,
                'tradesCount' => 312,
                'created' => '2025-06-20',
            ],
            [
                'id' => 'SQ_TR_GB_S_H4_011_v1.2.0',
                'shortName' => 'TR-GB-S-011',
                'family' => 'TR',
                'status' => 'retired',
                'sharpe' => 0.43,
                'profitFactor' => 0.88,
                'winRate' => 44.1,
                'maxDrawdown' => 28.5,
                'robustness' => 18,
                'symbol' => 'GBP/USD',
                'timeframe' => 'H4',
                'direction' => 'SHORT',
                'cumulativePnl' => -3250,
                'wfStatus' => 'ok',
                'wfDays' => 0,
                'tradesCount' => 178,
                'created' => '2025-04-15',
            ],
            [
                'id' => 'SQ_BT_EU_B_H1_007_v1.1.0',
                'shortName' => 'BT-EU-B-007',
                'family' => 'BT',
                'status' => 'retired',
                'sharpe' => 0.55,
                'profitFactor' => 0.95,
                'winRate' => 46.7,
                'maxDrawdown' => 25.3,
                'robustness' => 25,
                'symbol' => 'EUR/USD',
                'timeframe' => 'H1',
                'direction' => 'BOTH',
                'cumulativePnl' => -890,
                'wfStatus' => 'ok',
                'wfDays' => 0,
                'tradesCount' => 245,
                'created' => '2025-03-08',
            ],

            // ── PAUSED (one for variety) ─────────────────────────
            [
                'id' => 'SQ_NW_UC_B_H4_003_v1.4.0',
                'shortName' => 'NW-UC-B-003',
                'family' => 'NW',
                'status' => 'paused',
                'sharpe' => 1.12,
                'profitFactor' => 1.52,
                'winRate' => 52.6,
                'maxDrawdown' => 14.8,
                'robustness' => 60,
                'symbol' => 'USD/CAD',
                'timeframe' => 'H4',
                'direction' => 'BOTH',
                'cumulativePnl' => 670,
                'wfStatus' => 'due',
                'wfDays' => 55,
                'tradesCount' => 112,
                'created' => '2025-09-22',
            ],
        ];

        return Inertia::render('StrategyRegistry', [
            'strategies' => $strategies,
        ]);
    }
}
